### ISSUE TITLE
kernel-devel dependency not found on Centos 7.6

### ISSUE THREAD

**Issue by jcurryaz1** [Open-CAS/standalone-linux-io-tracer#128]
When installing on Centos 7.6
kernel-devel-3.10.0-957.el7.x86_64 not found in standard repos.  This has been replaced by kernel-devel-3.10.0-1062 so \setup-dependencies.sh fails

**Comment by tomaszrybicki** [comment]
This most likely happens if we try to install headers from an older kernel version which does not have headers in package manager, and package manager is not configured for this version. I'll close it for now, because we decided not to support this case.

The following solutions should work, either:
- Upgrade kernel version (yum update; reboot)
- Configure package manager for older version (yum distro-sync)
